name: Compile Linux Cloud
#on: [push]
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  LANG: "de_DE.UTF-8"

jobs:
  compile-linux-jre:
    runs-on: ubuntu-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@master

    - name: setup-graalvm-ce
      uses: gluonhq/setup-graalvm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         # GraalVM version. Default: latest
         graalvm: 'latest'
         # Java version. Since GraalVM 22, either java11, java17 or java23. Before GraalVM 22, empty. Default: java23
         jdk: 'java23'
         # Architecture flag. Available options are 'x86_64' (default) and 'aarch64'. The latter is available for M1 runners starting GraalVM 22.1.
         arch: 'x86_64'

    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Package
      run:  mvn -s settings.xml package
        
    - name: Show result1
      run: ls target/

    - name: JPackage
      run:  mkdir target/jpackage ;mvn jpackage:jpackage
        
    - name: Show result
      run: ls target/jpackage
      
    - name: Upload JRE RPM
      continue-on-error: true
      uses: garygrossgarten/github-action-scp@release
      with:
        verbose: false
        local: target/jpackage/mondtor-updater-${{ env.RELEASE_VERSION }}-1.x86_64.rpm
        remote: /var/www/html/mondtor-builds/linux/Mondtor-Updater-${{env.RELEASE_VERSION}}.rpm
        host: eden.rpgframework.de
        username: ghmondtor
        password: ${{ secrets.DEPLOY_PASSWORD }}
      
    - name: Upload JRE DEB
      continue-on-error: false
      uses: garygrossgarten/github-action-scp@release
      with:
        verbose: true
        local: target/jpackage/mondtor-updater_${{ env.RELEASE_VERSION }}-1_amd64.deb
        remote: /var/www/html/mondtor-builds/linux/Mondtor-Updater-${{env.RELEASE_VERSION}}.deb
        host: eden.rpgframework.de
        username: ghmondtor
        password: ${{ secrets.DEPLOY_PASSWORD }}
    