name: Compile Windows Cloud
on: [push]
#on:
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  LANG: "de_DE.UTF-8"

jobs:
  compile-windows-jre:
    runs-on: windows-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@master
 
    # Setup the Windows build environment
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Visual Studio shell
      uses: egor-tensin/vs-shell@v2

    - name: Get version (bash)
      continue-on-error: true
      shell: bash -l {0}
      run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: setup-graalvm-ce
      uses: taranion/setup-graalvm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Package
      run:  mvn -s settings.xml package
        
    - name: Show result1
      run: ls target/

    - name: Compile
      run:  mkdir target/jpackage ; mvn  -U -s settings.xml clean package jpackage:jpackage@win
      env: 
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_PASS: ${{ secrets.JFROG_PASS }}
        LANG: de_DE
        
    - name: Show result JPackage
      run: ls -l target/jpackage

    - name: Prepare staging 2
      continue-on-error: true
      run: mkdir Staging ; cp target/jpackage/Mondtor-*.msi Staging/
        
    - name: Show Staging content
      run: ls -l Staging
      
    - name: Deploy MSI
      uses: garygrossgarten/github-action-scp@release
      with:
        local: "target\\jpackage\\Mondtor-${{env.RELEASE_VERSION}}.msi"
        remote: /var/www/html/mondtor-builds/win/Mondtor-Updater-${{env.RELEASE_VERSION}}.msi
        host: eden.rpgframework.de
        username: ghmondtor
        password: ${{ secrets.DEPLOY_PASSWORD }}
       